### ISSUE TITLE
Flaky: smb2.ioctl.trim_simple setup CREATE hits DELETE_PENDING (an expected-SKIP test failing as a create-after-delete canary)

### ISSUE THREAD

**Issue by marmos91** [marmos91/dittofs#2107]
`smb2.ioctl.trim_simple` failed on PR #2092's SMB Conformance run with a setup CREATE rejected as `DELETE_PENDING`:

```
ioctl.c:325: status was NT_STATUS_DELETE_PENDING, expected NT_STATUS_OK: file create
ioctl.c:354: Expression `ok' failed: file create
ioctl.c:5683: Expression `ok' failed: src file create fill
ioctl.c:5725: setup trim error
```

Run 32782598426 attempt 1, job `smbtorture / memory`, 2026-08-24.

## The test is an expected SKIP, so this is a pure create-race canary

On develop's green run (32780634754, job 97601780412) the same test reports:

```
test: ioctl.trim_simple
skip: ioctl.trim_simple [ ../../source4/torture/smb2/ioctl.c:5734: trim not supported ]
smb2.ioctl.trim_simple                                               SKIP
```

DittoFS does not implement trim, so the test's normal outcome is SKIP at `ioctl.c:5734`. The PR run never reached that line — it failed at `ioctl.c:5725`, in the setup that creates and fills the source file, which runs *before* the trim capability is probed.

So `trim_simple` cannot fail for a trim-related reason. Its only failure mode is its setup CREATE, which makes it an unintentional canary for the create-after-delete window: `DELETE_PENDING` is what a CREATE gets while a handle with delete-on-close is still open on the path. The preceding test, `ioctl.sparse_qar_overflow`, passed immediately before, on the same path.

This is the same class as #743 (closed), which covered `DELETE_PENDING` plus requeued-CREATE residuals on the directory-lease paths.

## Not caused by #2092, structurally

The PR changes `pkg/block/journal`, `pkg/block/chunker`, and `ReconcileReclaim`. None of the three can execute in any smbtorture job:

- **No smbtorture profile constructs a `journal.Store`.** `journal.Open` has exactly one caller, `pkg/block/local/fs/fs.go:165`, and `bootstrap.sh` gives every profile `store block local add --type memory`. Both configs say so in their own headers — `configs/memory.yaml`: "memory metadata store + memory local block store"; `configs/badger-fs.yaml`: "BadgerDB metadata store + memory local block store" (the filesystem block store was removed in Phase 42, so the `-fs` profile names are legacy). `MemoryStore.Carve` is a self-contained implementation that packs each dirty file as one whole-file chunk and never enters `carveFile`/`packRuns`/the reap.
- **`chunker.Params.Validate` is reached only from `journal.Config.withDefaults`**, which needs a journal store; and `MemoryStore.Carve` deliberately does not run FastCDC.
- **`ReconcileReclaim`'s changed block is inside `for _, entry := range r.sharesSvc.DistinctRemoteStores()`**, which skips every share with `remoteConfigID == ""`. The memory profile configures no remote block store, so that list is empty. It is also a background sweep, not on the close/delete path.

The specific hypothesis worth ruling out was that the PR's extra whole-manifest read per reaped run slows the close/delete path enough to open this window. It cannot: the code that performs that read is never constructed in this process. The empirical cross-check agrees — `smbtorture / badger-fs` passed in the same run.

## Contributing conditions

That run had seven suites cut short by timeout with everything past the cut ungraded (`maxfid`, `aio_delay`, `lease`, `multichannel`, `notify`, `oplock`, `replay`) — #2098 in the wild, i.e. a loaded, timing-stressed run, which is what a create racing a delete needs.

## Worth noting for whoever picks this up

Comparing "green on develop" against this failure is misleading: develop **skips** this test. A green develop run is not evidence that the create path is sound, only that the trim probe was reached. The assertion that actually moved is the setup CREATE, and nothing on develop exercises it to a graded verdict either.

The sub-millisecond adjacency between `sparse_qar_overflow` completing and trim's create failing was reported to me from the attempt-1 log; I could not re-read it myself, since attempt 1's logs stopped being served once the job was superseded. The structural conclusion above does not depend on it.

**Comment by marmos91** [comment]
Did not reproduce on a clean run of the same branch — confirming this is a flake, not a reproducible red.

Run 32786721687, job `smbtorture / memory` (97620115088), on the rebased head `7d84d662` of the same PR:

```
test: ioctl.trim_simple
skip: ioctl.trim_simple [ ../../source4/torture/smb2/ioctl.c:5734: trim not supported ]
smb2.ioctl.trim_simple                                               SKIP
```

Identical to develop, and the whole SMB Conformance workflow was green (21 pass, 4 skipping). So the setup CREATE at `ioctl.c:5683` succeeded this time and the test reached the capability probe at `:5734` as it normally does.

That leaves the occurrence count at **1**, on a run that also had the seven #2098 timeout cuts. The failure window is real but narrow, and the structural argument in the issue body stands: the branch it failed on cannot reach the code that would explain it.

Worth keeping open rather than closing — the only thing that makes this test visible at all is the create-after-delete race, so it is the cheapest canary we have for that window. But it should be triaged as a rare timing flake, not as a regression.

**Comment by marmos91** [comment]
Reproduced structurally rather than statistically, and the mechanism is exact. Fix in #2120.

**The refusal has only two possible sources.** `STATUS_DELETE_PENDING` is returned from exactly two
places in the whole server, `internal/adapter/smb/handlers/create.go:1418` and `:1427`, and both
are the same gate — `isFileOrBaseDeletePending`, which is true only when an entry in the handler's
open-file table carries `DeletePending` or `BaseFileDeletePending`. So the failing CREATE saw a
handle in that table; nothing else can produce that status.

**Not its own handle.** In Samba 4.22.6 `test_setup_create_fill` (`ioctl.c:331`) is
`smb2_util_unlink(tree, fname)` — a CREATE with `FILE_DELETE_ON_CLOSE` then a CLOSE — followed by
`test_setup_open`, the CREATE that failed at `:325`. Those are serialized on one connection, and
`close.go` removes the handle from the table at step 10, before the CLOSE response is written.

**The previous test's handle.** `test_ioctl_sparse_qar_overflow` (`ioctl.c:5578`, registered
immediately before `trim_simple` at `:7716`) returns without ever closing `fh` — it leaks an open
handle on `FNAME`. `torture_suite_add_1smb2_test` gives every test a fresh connection and drops the
previous one with `talloc_free`, i.e. a bare socket close, no LOGOFF or TDIS. So that handle
survives until the server finishes tearing the dead connection down, and that teardown is
asynchronous with the next test's traffic. While it is still pending:

1. `smb2_util_unlink`'s CREATE succeeds — share access is `DELETE|READ|WRITE` on both opens.
2. Its CLOSE promotes delete-on-close, sees the leaked handle as another open on the same file, and
   per MS-FSA 2.1.5.4 propagates `DeletePending` to it instead of unlinking.
3. `test_setup_open`'s CREATE finds the file still present with a delete-pending handle on it →
   `STATUS_DELETE_PENDING`.

It heals as soon as the teardown lands, which is why the rerun was green and the count stayed at 1.

**The defect this exposes is ours.** There is already a barrier for exactly this: `SessionSetup`
calls `WaitForCleanup()` so a reconnecting client never sees a dying connection's shared state. It
was armed too late. `handleConnectionClose` runs `c.wg.Wait()` — draining every in-flight request
goroutine on the dead connection — and only then calls `cleanupSessions()`, which is where
`SignalPendingCleanup` lived. A SESSION_SETUP landing in that drain window sees an idle barrier and
goes straight through. On a runner with seven suites timing out, the drain is exactly where the
scheduling delay accumulates.

#2120 arms the barrier at the top of the close path so it spans the drain, and replaces the
`sync.WaitGroup` behind it — `Add` from zero with a `Wait` already in flight is the invalid
WaitGroup usage, and its consequence is precisely a waiter released although arming happened first
(the first version of the regression test tripped the race detector on it).

**Verified, not asserted.** `pkg/adapter/smb/cleanup_barrier_test.go` holds the connection's
request drain and checks whether the barrier lets a SESSION_SETUP-style wait through. With the
arming reverted it fails deterministically; with it, `-race -count=5` is clean.

**Ruled out / not claimed.**

- #2092 confirmed innocent, independently of the log: `journal.Open` still has exactly one caller
  (`pkg/block/local/fs/fs.go:165`) and every smbtorture profile in `bootstrap.sh` configures
  `store block local add --type memory`, so no journal store is ever constructed in that process.
- The unverified sub-millisecond adjacency from the attempt-1 log is not relied on anywhere above.
- The residual window is smaller, not zero: the server still learns the connection is gone only
  when its read loop wakes on EOF, and nothing can arm a barrier before that. Samba has the same
  asynchrony (a forked child releasing share modes as it exits), so a sufficiently starved runner
  can still land inside it.
- The leaked handle in `test_ioctl_sparse_qar_overflow` is an upstream test artifact and is not
  fixed here. It is what makes this test a canary at all.

Two adjacent defects found on the same seam and fixed in the same PR: a redundant `StoreOpenFile`
in delete-on-close propagation that could resurrect a handle its own CLOSE had removed (leaving a
delete-pending entry nothing reaps, so *every* later CREATE on that path answers DELETE_PENDING —
cascading rather than healing, so not this bug); and a panic guard in `cleanupSessions` that
released the panicking session's barrier count twice, opening the barrier while a session it never
reached still had open files.

**Comment by marmos91** [comment]
Fixed in #2120.
