### PR TITLE
fix(smb): arm the session-cleanup barrier before draining a dying connection

### LINKED ISSUE #2107: Flaky: smb2.ioctl.trim_simple setup CREATE hits DELETE_PENDING (an expected-SKIP test failing as a create-after-delete canary)
`smb2.ioctl.trim_simple` failed on PR #2092's SMB Conformance run with a setup CREATE rejected as `DELETE_PENDING`:

```
ioctl.c:325: status was NT_STATUS_DELETE_PENDING, expected NT_STATUS_OK: file create
ioctl.c:354: Expression `ok' failed: file create
ioctl.c:5683: Expression `ok' failed: src file create fill
ioctl.c:5725: setup trim error
```

Run 32782598426 attempt 1, job `smbtorture / memory`, 2026-08-24.

## The test is an expected SKIP, so this is a pure create-race canary

On develop's green run (32780634754, job 97601780412) the same test reports:

```
test: ioctl.trim_simple
skip: ioctl.trim_simple [ ../../source4/torture/smb2/ioctl.c:5734: trim not supported ]
smb2.ioctl.trim_simple                                               SKIP
```

DittoFS does not implement trim, so the test's normal outcome is SKIP at `ioctl.c:5734`. The PR run never reached that line — it failed at `ioctl.c:5725`, in the setup that creates and fills the source file, which runs *before* the trim capability is probed.

So `trim_simple` cannot fail for a trim-related reason. Its only failure mode is its setup CREATE, which makes it an unintentional canary for the create-after-delete window: `DELETE_PENDING` is what a CREATE gets while a handle with delete-on-close is still open on the path. The preceding test, `ioctl.sparse_qar_overflow`, passed immediately before, on the same path.

This is the same class as #743 (closed), which covered `DELETE_PENDING` plus requeued-CREATE residuals on the directory-lease paths.

## Not caused by #2092, structurally

The PR changes `pkg/block/journal`, `pkg/block/chunker`, and `ReconcileReclaim`. None of the three can execute in any smbtorture job:

- **No smbtorture profile constructs a `journal.Store`.** `journal.Open` has exactly one caller, `pkg/block/local/fs/fs.go:165`, and `bootstrap.sh` gives every profile `store block local add --type memory`. Both configs say so in their own headers — `configs/memory.yaml`: "memory metadata store + memory local block store"; `configs/badger-fs.yaml`: "BadgerDB metadata store + memory local block store" (the filesystem block store was removed in Phase 42, so the `-fs` profile names are legacy). `MemoryStore.Carve` is a self-contained implementation that packs each dirty file as one whole-file chunk and never enters `carveFile`/`packRuns`/the reap.
- **`chunker.Params.Validate` is reached only from `journal.Config.withDefaults`**, which needs a journal store; and `MemoryStore.Carve` deliberately does not run FastCDC.
- **`ReconcileReclaim`'s changed block is inside `for _, entry := range r.sharesSvc.DistinctRemoteStores()`**, which skips every share with `remoteConfigID == ""`. The memory profile configures no remote block store, so that list is empty. It is also a background sweep, not on the close/delete path.

The specific hypothesis worth ruling out was that the PR's extra whole-manifest read per reaped run slows the close/delete path enough to open this window. It cannot: the code that performs that read is never constructed in this process. The empirical cross-check agrees — `smbtorture / badger-fs` passed in the same run.

## Contributing conditions

That run had seven suites cut short by timeout with everything past the cut ungraded (`maxfid`, `aio_delay`, `lease`, `multichannel`, `notify`, `oplock`, `replay`) — #2098 in the wild, i.e. a loaded, timing-stressed run, which is what a create racing a delete needs.

## Worth noting for whoever picks this up

Comparing "green on develop" against this failure is misleading: develop **skips** this test. A green develop run is not evidence that the create path is sound, only that the trim probe was reached. The assertion that actually moved is the setup CREATE, and nothing on develop exercises it to a graded verdict either.

The sub-millisecond adjacency between `sparse_qar_overflow` completing and trim's create failing was reported to me from the attempt-1 log; I could not re-read it myself, since attempt 1's logs stopped being served once the job was superseded. The structural conclusion above does not depend on it.

### PR DESCRIPTION
**Pull request by marmos91**
Closes #2107.

## The premise held, and the failure has an exact mechanism

`smb2.ioctl.trim_simple` failed with its setup CREATE rejected `NT_STATUS_DELETE_PENDING`. The
issue is right that this has nothing to do with trim (the test's normal outcome is SKIP at
`ioctl.c:5734`, and the run never reached that line) and right that PR #2092 cannot have caused
it — re-verified here in two lines: `journal.Open` still has exactly one caller,
`pkg/block/local/fs/fs.go:165`, and every smbtorture profile in `bootstrap.sh` configures
`store block local add --type memory`, so no journal store is ever constructed in that process.

What the issue could not establish, and this PR does, is why the CREATE was refused. It is not a
statistical argument.

**`STATUS_DELETE_PENDING` has exactly two sources on the CREATE path**, both in
`internal/adapter/smb/handlers/create.go` (`:1418`, `:1427`), and both are the same gate:
`isFileOrBaseDeletePending`, which returns true only when an entry in the handler's open-file
table carries `DeletePending` or `BaseFileDeletePending`. So the failing CREATE necessarily saw a
handle in that table.

**It was not the test's own handle.** In Samba 4.22.6, `test_setup_create_fill` (`ioctl.c:331`)
is `smb2_util_unlink(tree, fname)` — a CREATE with `FILE_DELETE_ON_CLOSE` followed by a CLOSE —
and then `test_setup_open` (the CREATE that failed, at `ioctl.c:325`). Those are serialized on one
connection, and `close.go` removes the handle from the table at step 10, before the CLOSE response
is written. By the time the client sends the next CREATE, its own unlink handle is gone.

**It was the previous test's handle.** `test_ioctl_sparse_qar_overflow`, registered immediately
before `trim_simple` (`ioctl.c:7716`), returns without ever closing `fh` — it leaks an open handle
on `FNAME`. `torture_suite_add_1smb2_test` gives each test a fresh connection and tears the
previous one down with `talloc_free`, i.e. a bare socket close with no LOGOFF or TDIS. So the
leaked handle goes away only when the server finishes tearing down the dead connection, and that
teardown is asynchronous with respect to the next test's traffic. If it has not finished:

1. `smb2_util_unlink`'s CREATE succeeds (share access is `DELETE|READ|WRITE` on both opens).
2. Its CLOSE promotes delete-on-close, finds the leaked handle as another open on the same file,
   and per MS-FSA 2.1.5.4 propagates `DeletePending` to it instead of unlinking.
3. `test_setup_open`'s CREATE finds the file still present with a delete-pending handle on it →
   `STATUS_DELETE_PENDING`.

It then heals itself as soon as the teardown lands, which is why a rerun is green and why the
occurrence count stayed at 1.

## The actual defect: the barrier that should have prevented this is armed one step too late

DittoFS already has the mechanism for this. `SessionSetup` calls `WaitForCleanup()` precisely so
a reconnecting client never observes a dying connection's shared state. The bug is where it gets
armed.

`handleConnectionClose` (`pkg/adapter/smb/connection.go`) runs `c.wg.Wait()` — draining every
in-flight request goroutine on the dead connection — and only then calls `cleanupSessions()`,
which is where `SignalPendingCleanup` lived. A new connection's SESSION_SETUP that lands during
that drain sees an idle barrier and sails through, while the dead connection's open files are all
still in the table. Under a loaded runner (that run had seven suites cut short by timeout, i.e.
#2098 in the wild) the drain is exactly where the scheduling delay accumulates.

The barrier is now armed at the top of the close path, before the drain, with one count held
across the whole thing; the per-session counts `cleanupSessions` adds nest inside it. This closes
the window down to the goroutine wake on the socket EOF itself, which is on the same goroutine as
the arming and so has no further gap to give away.

## The barrier could also fail to hold when it *was* armed

The barrier was a `sync.WaitGroup`. Arming happens on whichever connection goroutine just lost its
socket; the waiter is a SESSION_SETUP on an unrelated connection. That means `Add` routinely runs
from a zero counter with a `Wait` already in flight — the one usage `sync.WaitGroup` documents as
invalid, and which the Go race detector rejects. It is not academic: a `Wait` that has already
sampled the counter as zero returns even though the `Add` happened first. The first version of the
regression test below tripped the detector on it.

`cleanupBarrier` (new, `internal/adapter/smb/handlers/cleanup_barrier.go`) replaces it with a
mutex-guarded counter plus an `idle` channel that is open while cleanups are outstanding. A waiter
that reads the channel after an `Add` is guaranteed to see it open. `WaitForCleanup` now selects
on that channel and its existing 3s timeout, which also drops the goroutine it used to spawn per
call.

## Second finding on the same seam: a re-Store that resurrects a closed handle

The delete-on-close propagation blocks (`close.go` twice, `handler.go` once) write `DeletePending`
onto sibling handles found by ranging the open-file table, and then called
`h.StoreOpenFile(other)`. `other` is the pointer the table already holds, so the write is visible
without it — the Store was redundant. Worse, when a sibling's own CLOSE removed it between the
`Range` and the Store, the Store put it back with `DeletePending` set and nothing left to reap it,
so *every* later CREATE on that path answered `DELETE_PENDING` for the life of the process.

This is not what #2107 observed — it would cascade rather than heal — so it is reported here as an
adjacent latent defect found while tracing the same gate, not as the cause. The fix is deleting
three redundant calls.

## Third finding, from review: the cleanup panic path released one count too many

`cleanupSessions`' panic guard retired a barrier count for every session the loop had not
*completed*. But `CleanupSession` retires its own count from a `defer`, which runs on the panicking
unwind as well — so the panicking session's count was released twice, and the barrier could reach
zero while a session the loop never reached still had its open files in the handle table. That is
the same early-open this PR exists to prevent, arriving by the panic path instead. The guard now
counts sessions whose count is already gone.

The `sync.WaitGroup` used to make that imbalance loud (it panics on a negative counter);
`cleanupBarrier.Done` cannot go negative without double-closing its channel, so an unbalanced Done
is logged at error instead of silently swallowed.

## The shape, and where else it appears

All three fixes above are one defect shape: **sample state, then act on the sample across a step or
lock boundary that lets the state change in between.** The barrier count was added after the drain
rather than before it; the panic guard counted completions rather than releases; the propagation
re-Stored an entry it had sampled by `Range` and that a concurrent CLOSE could have removed.

Two more instances in the same teardown path, checked while here:

- `removeChannelsAndPartition` samples `sess.ChannelCount()` and then tears the session down. A
  SESSION_SETUP binding a channel in between would destroy a session under a live channel. Arming
  the barrier at the top of the close path closes this one too, since the binder now waits — worth
  recording, because it was open for the same reason and is fixed by the same line.
- `close.go` decides "am I the last handle on this file?" at step 8 and removes itself from the
  table at step 10. Two concurrent last-handle closes can each see the other and each defer the
  delete, so the unlink is lost. `renameScanMu` covers steps 10–11 only; the step 8 scan is
  outside it. Filed as #2126 rather than folded in — it is a different failure (a lost delete, not
  an early-opened barrier), it predates this PR, and it wants its own reproduction.

## Verification

`internal/adapter/smb/handlers/cleanup_barrier_test.go` covers the barrier primitive itself
(zero value, a waiter that captured the channel before the last Done, re-arming, an unbalanced
Done, and concurrent Add/Done under `-race`).

`pkg/adapter/smb/cleanup_barrier_test.go` reproduces the window deterministically: hold the
connection's request drain, then check whether the cleanup barrier lets a SESSION_SETUP-style wait
through.

Without the arming change (fix reverted, everything else in place):

```
--- FAIL: TestConnectionClose_BarrierCoversRequestDrain (2.00s)
    cleanup_barrier_test.go:63: cleanup barrier stayed open while the closing connection was draining in-flight requests
FAIL
```

With it, `-race -count=5`:

```
ok  	github.com/marmos91/dittofs/pkg/adapter/smb	2.904s
```

`go build ./...`, `go vet ./...`, `gofmt`, `go test ./...` and `go test -race` over
`./internal/adapter/smb/... ./pkg/adapter/smb/...` are clean.

## What this does not claim

The residual window is smaller, not zero: the server still learns the connection is gone only when
its read loop wakes on EOF, and nothing can arm a barrier before that. Samba has the same
asynchrony (a forked child releasing share modes as it exits), so a sufficiently starved runner can
still land a CREATE inside it. The leaked handle in `test_ioctl_sparse_qar_overflow` is an upstream
test artifact and is not fixed here.

The sub-millisecond adjacency between `sparse_qar_overflow` completing and trim's create failing
was never re-readable (attempt 1's logs stopped being served once the job was superseded) and is
not relied on anywhere above; the argument is structural throughout.

### CODE REVIEW

File: internal/adapter/smb/handlers/handler.go [hunk 1]
```diff
@@ -1930,9 +1919,9 @@ func (h *Handler) cancelAsyncOpsForSession(sessionID uint64) {
 //
 // IMPORTANT: The caller must call SignalPendingCleanup(1) before calling
 // CleanupSession to ensure the cleanup barrier is visible to new sessions.
-// The WaitGroup decrement (Done) happens via defer.
+// The matching Done happens via defer.
```
[the remark this answers is not in the document]
Comment (marmos91) [reply internal/adapter/smb/handlers/handler.go]: Fixed in d4638fa0 — the contract now reads as one count per session the caller is about to clean up, and notes that the count is retired from a defer so it goes on a panicking unwind too.
